### ISSUE TITLE
CMake does not respect command-line settings

### ISSUE THREAD

**Issue by nschloe** [CGAL/cgal#2850]
When building CMake projects, the line
```
cmake -DCMAKE_BUILD_TYPE=Debug /path/to/project/
```
always sets the build type to `Debug`. With CGAL, however, the line
```
include(${CGAL_USE_FILE}) 
```
will always override it with `Release`. The same goes for many other settings, I suspect. `CXXFLAGS` is another I could identify; no matter what I do, CGAL will always set
```
-- USING CXXFLAGS = '-g -O2 -fdebug-prefix-map=/build/cgal-qW_yGY/cgal-4.9=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -frounding-math -O3 -DNDEBUG'
```
This makes it impossible to build certain programs on our test environment as `-g` simply eats up too much memory for the box. I don't know why it specified `-DNDEBUG` _and_ `-g` either; those options seem to contract each other.

**Comment by sloriot** [comment]
This was fixed by #1436 and will be part of CGAL 4.12

**Comment by nschloe** [comment]
Great, thank you!

**Comment by sloriot** [comment]
Thanks for taking time to report :)

**Comment by lrineau** [comment]
As Sébastien (@sloriot) pointed out, both this bug and #2849 are probably fixed since #1436 is merged into `master`. (I have not yet verified.)

The old CMake code still present in CGAL-4.11 was dated from the CGAL-3.4 in 2008-2009, when CMake has been first used in CGAL. At that time, the recent CMake versions were CMake 2.4/2.6, and the CMake API was very different and a lot less powerful than it is now. That explains why that old CMake code used ugly hacks, modifying `CMAKE_CXX_FLAGS` directly, for example. The syntax revolution of CMake 2.8.13 and 3.0, has changed a lot, and it has taken us time to update our CMake code to modern CMake usages.

Two good news:
  - as we said, it is fixed in `master`, and so that will be different in CGAL-4.12 (coming soon),
  - even if you use an existing CGAL version <= 4.11, there is a workaround: set the cache variable `CGAL_DONT_OVERRIDE_CMAKE_FLAGS` to `TRUE`, before the first time the `${CGAL_USE_FILE}` is include!

Add for example in your CMakeLists.txt:
```cmake
set(CGAL_DONT_OVERRIDE_CMAKE_FLAGS TRUE CACHE BOOL "")
```
or set the variable from the CMake command line, with `-DCGAL_DONT_OVERRIDE_CMAKE_FLAGS=TRUE`.
