### ISSUE TITLE
Filtered construction?

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#44]
In CGAL, there are efficient exact predicates, using the [`Filtered_predicate` class template](http://doc.cgal.org/latest/Kernel_23/classCGAL_1_1Filtered__predicate.html) that can wrap a pair (*interval predicate*, *exact predicate*).

For constructions, that is a lot more complicated. Should not we try to provide a `Filtered_construction`, extending the ideas developed in the `Robust_circumcenter_traits_3` of Mesh_3?

(I fill this issue as a reminder, link an entry in a TODO list.)

**Comment by mkaravel** [comment]
I have implemented something along these lines in the `Segment_Delaunay_graph_2` package.
See: https://github.com/CGAL/cgal/blob/master/Segment_Delaunay_graph_2/include/CGAL/Filtered_construction.h

**Comment by lrineau** [comment]
@mkaravel, if I understand your code correctly, the switch from filtering to exact is done when there is an uncertainty in the sign of any intermediate expression used in the construction. Is that right?

**Comment by mkaravel** [comment]
@lrineau Yes.

**Comment by mglisse** [comment]
"the ideas developed in the Robust_circumcenter_traits_3 of Mesh_3": could you maybe expand on what that is? As far as I can see, it converts the input to an exact kernel, does the exact construction, then converts back to the original kernel. That is slow. It gives a result that is as close to the "truth" as can be represented in this kernel. It still does not guarantee that the result is equidistant from the 3 input points, or whatever it is we might want to guarantee. My main issue is that the goal is not clearly stated. Is it a construction with a "better" precision? Is it a combinatorially correct construction (as in Menelaos' case, decisions are exact even if computations are not; something similar was discussed for Intersect_23)?

**Comment by lrineau** [comment]
There have been several different versions of that traits class. The [current version][current] computes the denominator using `double`, then checks if it is 0. If it is non-zero, then the construction using doubles continue, otherwise it does what you said: to exact, and convert back the result to double. Then in Mesh_3, there is an extra check that tests if the "circumcenter" is in the sphere or not (using a filtered predicate). If the circumcenter is so wrong that it is not in the sphere, then it is recomputed using an exact construction.

[current]: https://github.com/CGAL/cgal/blob/6649036c8071316735bab8ae5730ad6bcd2f3741/Mesh_3/include/CGAL/Mesh_3/Robust_weighted_circumcenter_filtered_traits_3.h

I understand that all those ideas cannot be implemented generically. I am trying to start a discussion, to gather other ideas. Maybe the first computation could be done using `Interval_nt` (switching to exact as soon as there is an uncertain sign somewhere), then there could be a functor, given as a template parameter, to check the validity of the construction. The implementation would switch to exact if the constructed inexact object is not good enough according to the functor.

**Comment by mglisse** [comment]
Having a validating predicate (In_sphere in your case) makes it well defined, that's good. We could indeed wrap constructions, so they would first try an inexact version (with double or Interval_nt), validate it, then go for the exact version is that failed (should we also validate the converted exact solution and tell the user if that failed as well?).
It isn't clear if that is better than providing 2 versions of the functor, fast vs precise, and let users (=algorithms) do whatever testing they feel is needed.
Using double (pure speed, relying on the validating functor) vs using Interval_nt (combinatorially correct, medium speed) indicates that a 3rd version could make sense. The more versions there are, the harder it is to guess what combination an algorithm is likely to want, so exposing the bricks may be easier. In one of the re-architecture-the-kernel discussions, this was Get_functor<Construct_circumcenter_tag, OPT> where OPT could be Fast_tag, Precise_tag, Exact_tag, Combinatorial_tag, whatever we want to provide. Although exposing the Interval_nt version seems problematic, so we could maybe provide 3 versions: the fast version (double), the as-exact-as-possible version, and the combinatorially-good version (filter interval-exact), where in meshing you would first call the double version, check the result (let's hope inf/nan are handled correctly when there was a division by 0...) then call the as-exact-as-possible version.

**Comment by sgiraudot** [comment]
Can this issue be closed or is it still something to do?

**Comment by lrineau** [comment]
Unfortunately, we still do not have a solution for this feature request.

**Comment by lrineau** [comment]
Note that `<CGAL/Filtered_construction.h>` is now in `Filtered_kernel/include/` since #1530 was merged.

**Comment by sloriot** [comment]
After a discussion with @MaelRL  one way to solve the precision issue of filtered constructions could be:

```
diff --git a/Cartesian_kernel/include/CGAL/Cartesian_converter.h b/Cartesian_kernel/include/CGAL/Cartesian_converter.h
index 33f941b330..0f75679cb5 100644
--- a/Cartesian_kernel/include/CGAL/Cartesian_converter.h
+++ b/Cartesian_kernel/include/CGAL/Cartesian_converter.h
@@ -220,6 +220,12 @@ public:
        return Point_2(c(a.x()), c(a.y()));
     }
 
+    bool has_enough_precision(const const typename K1::Point_2 &a) const
+    {
+      return a.x().width() < get_relative_precision_of_to_double() &&
+             a.y().width() < get_relative_precision_of_to_double();
+    }
+
     typename K2::Weighted_point_2
     operator()(const typename K1::Weighted_point_2 &a) const
     {
diff --git a/Filtered_kernel/include/CGAL/Filtered_construction.h b/Filtered_kernel/include/CGAL/Filtered_construction.h
index 16e16f4cad..f9b1131e97 100644
--- a/Filtered_kernel/include/CGAL/Filtered_construction.h
+++ b/Filtered_kernel/include/CGAL/Filtered_construction.h
@@ -90,17 +90,18 @@ public:
     Protect_FPU_rounding<Protection> P1;
     try
     {
-      return From_Filtered( Filter_construction(To_Filtered(a1),
-                                               To_Filtered(a2),
-                                               To_Filtered(a3)) );
+      typename Filtered_construction::result_type res = Filter_construction(To_Filtered(a1),
+                                                                            To_Filtered(a2),
+                                                                            To_Filtered(a3)) );
+      if ( From_Filtered.has_enough_precision(res) )
+        return From_Filtered(res)
     }
     catch (Uncertain_conversion_exception&)
-    {
-      Protect_FPU_rounding<!Protection> P(CGAL_FE_TONEAREST);
-      return From_Exact( Exact_construction(To_Exact(a1),
-                                           To_Exact(a2),
-                                           To_Exact(a3)) );
-    }
+    {}
+    Protect_FPU_rounding<!Protection> P(CGAL_FE_TONEAREST);
+    return From_Exact( Exact_construction(To_Exact(a1),
+                                        To_Exact(a2),
+                                        To_Exact(a3)) );
   }
 
 };
```

We have to do some tricks to avoid call `width()` as a member type to restrict it `Interval_nt` but the global idea is here.

**Comment by mglisse** [comment]
In https://github.com/mglisse/cgal/tree/NewKernel_d-Epack-glisse I used the approach I mentioned in https://github.com/CGAL/cgal/issues/3153 of having the precision test in the conversion from Interval_nt to double. It seems simpler than having specific code for each object converter.

**Comment by sloriot** [comment]
Using a free function to get the precision (infinity by default) I agree. Probably a dedicated exception should be used.
