### ISSUE TITLE
Performance degradation of boolean set operation when upgrade CGAL from 5.2.3 to 5.3.

### ISSUE THREAD

**Issue by Supranaturaler** [CGAL/cgal#6092]
## Issue Details

Performance degradation of boolean set operation when upgrade CGAL from 5.2.3 to 5.3.
Here is a simple test:
CGAL 5.2.3
![image](https://user-images.githubusercontent.com/40469886/139450862-2e6da29b-ebde-4303-a906-f89bb7740650.png)

CGAL 5.3
![image](https://user-images.githubusercontent.com/40469886/139450454-e622a460-bd4f-4fbd-9da6-f9259f4f3d49.png)

## Source Code
```
#include <iostream>
#include <vector>

#include "CGAL/Exact_predicates_exact_constructions_kernel.h"
typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
typedef Kernel::Point_2 Point_2;

#include "CGAL/Polygon_2.h"
typedef CGAL::Polygon_2<Kernel> Polygon_2;

#include "CGAL/Polygon_set_2.h"
typedef CGAL::Polygon_set_2<Kernel> Polygon_set_2;

int main(int argc, char* argv[])
{
    auto startTime = std::chrono::high_resolution_clock::now();
    const size_t polygonSize = 2000;
    std::vector<Polygon_2> vecPolygons(polygonSize);
    for (size_t i = 0; i < polygonSize; ++i)
    {
        vecPolygons[i].push_back(Point_2(i - 0.5, i - 0.5));
        vecPolygons[i].push_back(Point_2(i + 0.5, i - 0.5));
        vecPolygons[i].push_back(Point_2(i + 0.5, i + 0.5));
        vecPolygons[i].push_back(Point_2(i - 0.5, i + 0.5));
    }
    Polygon_set_2 polygonSet;
    polygonSet.join(vecPolygons.begin(), vecPolygons.end());

    for (size_t i = 0; i < polygonSize; ++i)
    {
        polygonSet.do_intersect(vecPolygons[i]);
    }
    
    auto endTime = std::chrono::high_resolution_clock::now();
    auto diffTime = endTime - startTime;
    std::cout << "Total cost: " << diffTime.count() * 1e-9 << std::endl;
    return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 11 home basic 64 bits
* Compiler: MSVC-2019-Community
* Release or debug mode: Release 
* Specific flags used (if any):
* CGAL version: CGAL5.2.3 CGAL5.3
* Boost version: boost_1_76_0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
In the CGAL project, we care a lot about performance. And performance regressions across releases are the worst kind of bugs, because they are difficult to detect using the automatic testing we run daily. We try to be careful but sometimes such a bug slips through around watch.

**Comment by Supranaturaler** [comment]
@sloriot  Still performance regression in some cases.

## Issue Details
I have merged the code in #6094 and test another case. There is stll performance regression. Please check!
CGAL 5.2.2
![image](https://user-images.githubusercontent.com/40469886/140047823-103a947a-6254-4966-acc9-ac26159b23c6.png)

CGAL 5.4 with #6094 merged
![image](https://user-images.githubusercontent.com/40469886/140048106-a285e15d-5c3a-4eb3-bb8f-37373306b7c5.png)


## Source Code
```
#include <iostream>
#include <vector>

#include "CGAL/Exact_predicates_exact_constructions_kernel.h"
typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
typedef Kernel::Point_2 Point_2;

#include "CGAL/Polygon_2.h"
typedef CGAL::Polygon_2<Kernel> Polygon_2;

#include "CGAL/Polygon_set_2.h"
typedef CGAL::Polygon_set_2<Kernel> Polygon_set_2;

int main(int argc, char* argv[])
{
    auto startTime = std::chrono::high_resolution_clock::now();
    const size_t polygonSize = 40000;
    std::vector<Polygon_2> vecPolygons(polygonSize);
    for (size_t i = 0; i < polygonSize; ++i)
    {
        vecPolygons[i].push_back(Point_2(i - 0.5, -1));
        vecPolygons[i].push_back(Point_2(i + 0.5, -1));
        vecPolygons[i].push_back(Point_2(i + 0.5, 1));
        vecPolygons[i].push_back(Point_2(i - 0.5, 1));
    }
    Polygon_set_2 polygonSet;
    polygonSet.join(vecPolygons.begin(), vecPolygons.end());

    Polygon_set_2 intersectSet, emptySet;
    intersectSet.intersection(polygonSet, emptySet);

    for (size_t i = 0; i < polygonSize; ++i)
    {
        Polygon_set_2 singlePolygonSet(vecPolygons[i]), singleIntersectSet;
        singleIntersectSet.intersection(singlePolygonSet, intersectSet);
    }

    auto endTime = std::chrono::high_resolution_clock::now();
    auto diffTime = endTime - startTime;
    std::cout << "Total cost: " << diffTime.count() * 1e-9 << std::endl;
    return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 11 home basic 64 bits
* Compiler: MSVC-2019-Community
* Release or debug mode: Release 
* Specific flags used (if any):
* CGAL version: CGAL5.2.2 CGAL5.4 with #6094 merged
* Boost version: boost_1_76_0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Are you sure you have release builds in both cases? On my machine I had similar timing last Friday.

**Comment by Supranaturaler** [comment]
> Are you sure you have release builds in both cases? On my machine I had similar timing last Friday.

I test again and get the same result. Watch out, this is a new test cast, not the old one last Friday. The old test case last Friday is passed.
![image](https://user-images.githubusercontent.com/40469886/140242776-df0293de-1fe1-407f-b951-7f0b8e6e45da.png)

**Comment by sloriot** [comment]
It turns out that the issue comes from the change of containers for simplices. `intersectSet` is empty after having being cleared. But since there is a sort of garbage collection in the new container used, there were some issue to handle the freelist elements. It is now fixed in the branch. Would you mind give it another try? (btw is it expected by `intersectSet` is empty?)

**Comment by Supranaturaler** [comment]
Sorry to bother you. The performance degradation still exist. Here is the case I met.

## Issue Details
Dataset
[dataset1.txt](https://github.com/CGAL/cgal/files/7481732/dataset1.txt)
[dataset2.txt](https://github.com/CGAL/cgal/files/7481734/dataset2.txt)

CGAL 5.2.2
![image](https://user-images.githubusercontent.com/40469886/140481579-cdf64bb4-dcfa-4b0c-8077-e45dc4744276.png)

CGAL 5.4 with #6094 merged
![image](https://user-images.githubusercontent.com/40469886/140481922-44ae7b34-560c-44a5-a3da-59f367e4c445.png)

## Source Code
```
#include <iostream>
#include <vector>
#include <fstream>

#include "CGAL/Exact_predicates_exact_constructions_kernel.h"
typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
typedef Kernel::Point_2 Point_2;

#include "CGAL/Polygon_2.h"
typedef CGAL::Polygon_2<Kernel> Polygon_2;

#include "CGAL/Polygon_set_2.h"
typedef CGAL::Polygon_set_2<Kernel> Polygon_set_2;

void ParseDataSet(const std::string& filePath, std::vector<Polygon_2>& vecPolygons)
{
    std::ifstream fileStream(filePath, std::ios::in);
    if (!fileStream)
    {
        return;
    }

    size_t polygonSize = 0;
    fileStream >> polygonSize;
    vecPolygons.resize(polygonSize);
    for (size_t i = 0; i < polygonSize; ++i)
    {
        int vertexSize = 0;
        fileStream >> vertexSize;
        vecPolygons[i].container().reserve(vertexSize);

        for (size_t j = 0; j < vertexSize; ++j)
        {
            double x = 0.0, y = 0.0;
            fileStream >> x >> y;
            vecPolygons[i].push_back(Point_2(x, y));
        }
    }
}

int main(int argc, char* argv[])
{
    auto startTime = std::chrono::high_resolution_clock::now();

    std::vector<Polygon_2> vecPolygons1;
    ParseDataSet("dataset1.txt", vecPolygons1);
    Polygon_set_2 polygonSet1;
    polygonSet1.join(vecPolygons1.begin(), vecPolygons1.end());

    std::vector<Polygon_2> vecPolygons2;
    ParseDataSet("dataset2.txt", vecPolygons2);
    Polygon_set_2 polygonSet2;
    polygonSet2.join(vecPolygons2.begin(), vecPolygons2.end());

    Polygon_set_2 intersectSet;
    intersectSet.intersection(polygonSet1, polygonSet2);

    for (const Polygon_2& polygon : vecPolygons1)
    {
        Polygon_set_2 singlePolygonSet(polygon), singleIntersectSet;
        singleIntersectSet.intersection(singlePolygonSet, intersectSet);
    }

    auto endTime = std::chrono::high_resolution_clock::now();
    auto diffTime = endTime - startTime;
    std::cout << "Total cost: " << diffTime.count() * 1e-9 << std::endl;
    return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 11 home basic 64 bits
* Compiler: MSVC-2019-Community
* Release or debug mode: Release 
* Specific flags used (if any):
* CGAL version: CGAL5.2.2 CGAL5.4 with #6094 merged
* Boost version: boost_1_76_0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
You are not bothering us, your input is actually very valuable. I've updated the branch and I now have a better runtime in your 3 cases when using that branch. Could you give it a try?

**Comment by Supranaturaler** [comment]
Nice work! The performance degradation I met seemed to be solved. Waiting for the 5.4 version to be released.
