### ISSUE TITLE
Mesh_3 - crash in test 

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#7406]
## Issue Details

The test `test_meshing_3D_gray_image_deprecated.cpp` fails with seed 
`CGAL::get_default_random() = CGAL::Random(1681938963);`

It is visible [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-227/Mesh_3/TestReport_lrineau_Fedora-rawhide.gz)

## Environment

* Compiler: MSVC 2022 (at least)
* Release or debug mode: debug
* CGAL version: master
* Boost version: 1.80

**Comment by lrineau** [comment]
With the seed, I can reproduce the bug with `master` (5.6-dev), but also 5.5, 5.4, 5.3, 5.2, 5.1. And I gave because with 5.0 I got a CMake error.

So, that is an old bug, revealed by that seed.

**Comment by afabri** [comment]
Can we also produce the bug with non-deprecated code?

**Comment by janetournois** [comment]
I just made some experiments.
Both `test_meshing_3D_gray_image` and `test_meshing_3D_gray_image_deprecated` were failing with the seed `1681938963` in CGAL-5.5.2.
None of them is failing in CGAL-5.6-beta1.

It would be good that someone on another platform gives it a try before we close this issue, but it seems it has been fixed!

**Comment by sloriot** [comment]
I can reproduce the error with 5.5.x branch with the seed for `test_meshing_3D_gray_image_deprecated` and with 5.6.x-branch. The test is gone in master but it is still present in `97097f1f040472b2fa8b02d778ecb22b55109d05` that the commit before the removal of the test. `test_meshing_3D_gray_image` works with the seed in the two release branches and master.

@janetournois @MaelRL can we discuss it quickly this afternoon?
